#!/bin/bash
# This filter avoids submitting tokens to the git repo. To use this add the following to your .git/config:
#
# [filter "remove-tokens"]
# clean  = .gitfilters/remove-tokens-clean
# smudge = .gitfilters/remove-tokens-smudge
set -e
for file in examples/*.tfvars; do
  if [ -f /tmp/$(basename $file) ]; then
    echo "Restoring tokens to $file..."
    TOKEN=$(cat /tmp/$(basename $file))
    sed -i "s/\(cvp_download_token.*=\) \"PLACE_YOUR_PORTAL_TOKEN_HERE\"/\1 \"$TOKEN\"/g" $file
    rm -f /tmp/$(basename $file)
  fi
done