#!/bin/bash
# This filter avoids submitting tokens to the git repo. To use this add the following to your .git/config:
#
# [filter "remove-tokens"]
#   clean  = .gitfilters/remove-tokens-clean
#   smudge = .gitfilters/remove-tokens-smudge
set -e
for file in examples/*.tfvars; do
  TOKEN=$(grep cvp_download_token $file |cut -f2 -d\")
  if [[ $TOKEN && $TOKEN != "PLACE_YOUR_PORTAL_TOKEN_HERE" ]]; then
    echo "Sanitizing tokens in $file..."
    echo $TOKEN > /tmp/$(basename $file)
    sed -i 's/\(cvp_download_token.*=\) ".*"/\1 "PLACE_YOUR_PORTAL_TOKEN_HERE"/g' $file
  fi
done