#!/bin/bash
# This filter avoids submitting tokens to the git repo. To use this add the following to your .git/config:
#
# [filter "remove-tokens"]
#   clean  = .gitfilters/remove-tokens-clean
#   smudge = .gitfilters/remove-tokens-smudge
set -e
sed 's/\(cvp_download_token.*=\) ".*"/\1 "PLACE_YOUR_PORTAL_TOKEN_HERE"/g'